// Curated list of popular Google Fonts. Users can also type a custom font name
// in the picker — anything Google Fonts serves via the css2 API will work.
export const POPULAR_GOOGLE_FONTS: string[] = [
  "Jost",
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Nunito",
  "Nunito Sans",
  "Raleway",
  "Source Sans 3",
  "Work Sans",
  "Rubik",
  "Mulish",
  "Manrope",
  "DM Sans",
  "Plus Jakarta Sans",
  "Space Grotesk",
  "IBM Plex Sans",
  "Karla",
  "Barlow",
  "Kanit",
  "Oswald",
  "Bebas Neue",
  "Archivo",
  "Fira Sans",
  "PT Sans",
  "Noto Sans",
  "Quicksand",
  "Ubuntu",
  "Cabin",
  "Titillium Web",
  "Heebo",
  "Dosis",
  "Public Sans",
  "Assistant",
  "Josefin Sans",
  "Hind",
  "Prompt",
  "Signika",
  "Sora",
  "Urbanist",
  "Figtree",
  "Onest",
  "Outfit",
  "Playfair Display",
  "Merriweather",
  "Lora",
  "PT Serif",
  "Cormorant Garamond",
  "EB Garamond",
  "Crimson Text",
  "Bitter",
  "Roboto Slab",
  "Roboto Mono",
  "JetBrains Mono",
  "Fira Code",
  "Space Mono",
  "IBM Plex Mono",
  "Source Code Pro",
];

export function googleFontsCss2Url(family: string): string {
  const encoded = family.trim().replace(/\s+/g, "+");
  return `https://fonts.googleapis.com/css2?family=${encoded}:wght@400;500;600;700;800&display=swap`;
}
